set_known_position:
  description: Set position aquired outside of this component without triggering action
  target:
    entity:
      domain: cover
  fields:
    position:
      description: position of cover, between 0 and 100 (inclusive)
      example: 50
    confident:
      description: optional (default is false) - if we are confident in this position, i.e. affects if state is assumed or not. To be used for example with a contact sensor confirming that the position was really reached.
      example: True
    position_type:
      description: optional (default is target) - specifies if the position we are passing in is the target or the current position. Defaults to target meaning we will transition slider from current posution to given target. Specifiying current will set to the current position immediately.
      example: current
set_known_action:
  description: Action of open, stop or close captured outside of HA, trigger cover response in HA without triggering action
  target:
    entity:
      domain: cover
  fields:
    action:
      description: must be one of open, close or stop
      example: open
